### ISSUE TITLE
[iOS/Android] flutter_package_import example > LateInitializationError: Field _instance error

### ISSUE THREAD

**Issue by devibrahimkarahan** [IVLIVS-III/dart_python_ffi#18]
When i tried to run example flutter_package_import app in android or ios, im getting an error

I cant see any ios/android folder in example apps, Is it possible to use this library in iOS/Android apps?

```
E/flutter (11838): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_instance@287145062' has not been initialized.
E/flutter (11838): #0      PythonFfiDelegate._instance (package:python_ffi_interface/src/delegate.dart)
E/flutter (11838): #1      PythonFfiDelegate.instance (package:python_ffi_interface/src/delegate.dart:18:53)
E/flutter (11838): #2      PythonFfi.initialize (package:python_ffi/src/python_ffi_base.dart:39:31)
E/flutter (11838): #3      initialize (package:flutter_package_export/flutter_package_export.dart:9:28)
E/flutter (11838): #4      main (package:flutter_package_import/main.dart:6:9)
E/flutter (11838): #5      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (11838): #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (11838): #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (11838): 
```

**Comment by IVLIVS-III** [comment]
@devibrahimkarahan No, Android and iOS are not supported out of the box at this point in time.
See [this comment](https://github.com/IVLIVS-III/dart_python_ffi/issues/3#issuecomment-1837201194) for details.
